name: Call Lambda

on:
  push:
    branches: [ main ]

jobs:
  call-lambda:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Call AWS Lambda
      run: |
        curl -X POST ${{ secrets.LAMBDA_URL }} \
        -H "Content-Type: application/json" \
        -d '{"message":"Hello from GitHub"}'
